import arcade

WINDOW_TITLE = "Doom-like Stage 1"
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

BACKGROUND_COLOR = arcade.color.BLACK

PLAYER_WIDTH = 30
PLAYER_HEIGHT = 40
PLAYER_COLOR = arcade.color.DARK_GREEN
PLAYER_START_X = WINDOW_WIDTH // 2
PLAYER_START_Y = WINDOW_HEIGHT // 2

WALL_COLOR = arcade.color.DARK_SLATE_GRAY
WALL_THICKNESS = 20
WALL_LENGTH_LONG = 300
WALL_LENGTH_SHORT = 200

WALL_TOP_X = WINDOW_WIDTH // 2
WALL_TOP_Y = WINDOW_HEIGHT - WALL_THICKNESS // 2
WALL_BOTTOM_X = WINDOW_WIDTH // 2
WALL_BOTTOM_Y = WALL_THICKNESS // 2
WALL_LEFT_X = WALL_THICKNESS // 2
WALL_LEFT_Y = WINDOW_HEIGHT // 2
WALL_RIGHT_X = WINDOW_WIDTH - WALL_THICKNESS // 2
WALL_RIGHT_Y = WINDOW_HEIGHT // 2

INNER_WALL_X = WINDOW_WIDTH // 2
INNER_WALL_Y = WINDOW_HEIGHT // 2 + WALL_LENGTH_SHORT // 2

WALL_SPECS = [
    (WALL_TOP_X, WALL_TOP_Y, WALL_LENGTH_LONG, WALL_THICKNESS),
    (WALL_BOTTOM_X, WALL_BOTTOM_Y, WALL_LENGTH_LONG, WALL_THICKNESS),
    (WALL_LEFT_X, WALL_LEFT_Y, WALL_THICKNESS, WALL_LENGTH_LONG),
    (WALL_RIGHT_X, WALL_RIGHT_Y, WALL_THICKNESS, WALL_LENGTH_LONG),
    (INNER_WALL_X, INNER_WALL_Y, WALL_LENGTH_SHORT, WALL_THICKNESS),
]


def validate_constants() -> None:
    assert WINDOW_WIDTH > 0
    assert WINDOW_HEIGHT > 0
    assert PLAYER_WIDTH > 0
    assert PLAYER_HEIGHT > 0
    assert WALL_THICKNESS > 0
    assert WALL_LENGTH_LONG > 0
    assert WALL_LENGTH_SHORT > 0


if __name__ == "__main__":
    validate_constants()
    print("Constants validated.")
